### ISSUE TITLE
Is dit echt een `<a>`?

### ISSUE THREAD

**Issue by KrijnHoetmer** [Stefan-Espant/fix-the-flow-interactive-website#12]
Zijn dit wel links? Of eigenlijk iets anders? (Tip: kijk ook eens naar het `<details>` element: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details)

https://github.com/Stefan-Espant/fix-the-flow-interactive-website/blob/5f750d24c198be4d2110f1b5fe5738fdb67fb66d/checklist.html#L164-L170

**Comment by Stefan-Espant** [comment]
Het zijn technisch gezien `buttons`. Ook had ik gekeken naar de `detail` tags maar ik wilde custom collapse sections maken en animeren.
