### ISSUE TITLE
The feedback micro interaction misses an animation

### ISSUE THREAD

**Issue by joostf** [Stefan-Espant/fix-the-flow-interactive-website#4]
https://github.com/Stefan-Espant/fix-the-flow-interactive-website/blob/f7873963e1461e8b12c7c4ec2efd4a30d04b8bdf/styles/style.css#L851-L853

The display property isn't animatable

**Comment by Stefan-Espant** [comment]
De `display` property heb ik aangepast naar `opacity` en de waardes 1 en 0 gegeven.
