### ISSUE TITLE
Cleaner naming convention?

### ISSUE THREAD

**Issue by joostf** [Stefan-Espant/fix-the-flow-interactive-website#6]
https://github.com/Stefan-Espant/fix-the-flow-interactive-website/blob/f7873963e1461e8b12c7c4ec2efd4a30d04b8bdf/index.html#L104

this:
```
<footer class="sticky">
```

instead of this:
```
<footer class="footer-sticky">
```

(opinionated!)

**Comment by Stefan-Espant** [comment]
Gefixed, goeie oplossing en toepassing van de DRY-methode.
