### ISSUE TITLE
Don't use BR element for layout

### ISSUE THREAD

**Issue by joostf** [Stefan-Espant/fix-the-flow-interactive-website#7]
https://github.com/Stefan-Espant/fix-the-flow-interactive-website/blob/f7873963e1461e8b12c7c4ec2efd4a30d04b8bdf/index.html#L44

Fix this in CSS instead

**Comment by Stefan-Espant** [comment]
Alle brakes heb ik gewist en voor de subtitels een `margin-top` gegeven.
